name: Automate-Docker-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy API
      run: |
        # Assuming your Dockerfile is in the repository root
        docker build -t ezopsimg .
        sudo docker stop $(sudo docker ps -a --latest -q) || true
        sudo docker rm $(sudo docker ps -a --latest -q) || true
        docker run -d -p 49160:8080 --name $(sudo docker ps -a --latest -q) ezopsimg
