name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull updates
        run: git pull origin main

      - name: Docker build image
        run: sudo docker build -t ezopsimg .

      - name: Docker Stop OldConteiner
        run: sudo docker stop ezopsconteiner || true

      - name: Docker remove old conteiner
        run: sudo docker rm ezopsconteiner || true

      - name: Docker run new conteiner based on image
        run: sudo docker run -d -p 49162:8080 --name ezopsconteiner ezopsimg
