name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      run: |
        # Replace with your EC2 instance details
        EC2_IP=35.153.71.198
        SSH_PRIVATE_KEY=MIIEowIBAAKCAQEAjzrGlgEP2iuvUozXwqae8iywaZDkKAtwWmgkNB+tiYJJpZ6CX9dR029+7Vdbi3gn+loIri3suth5HwdHLcEFcPCH3EHRcluUq8R29ygdk1YN3dOmA66C9lckxSpODClKhOCSmzaW7pXPbejnrra5KIeymb80/6HLsWfnnEK6XH0+4mfUJbOpROmkaL9wvanD5Q8yez6Lleu+WbAtSYirGKj0+rZ57fnX/8mJ50wlY7Rg3Voa+kJ8s1mvtsDtx0DvFCIvGcBK9y6gg6PL6o+htfKFL0vOGfB0ERtUAbbMJlp+ah1xNU6/fYyBD/uOuKiOCbetnjKGcC6iRCnKGI1wiwIDAQABAoIBAHXQjxFMhlGbpXdtyvyeOhhSkjoDqOkXn69+AmmttP1rYlENdYiIgRI+oFVyiibLC3dvH7zGofd/oQHY5r/ICkXAVMDkkvhSRJSV4pWjNdC/9GAHfIOCxM8FF4XnKpPuUxHB+FYcLULLj/iEoC6ituOT22GEWn/8AqVHJsjuSoVQb4I+VVCWaw8UcFvgC+lIW0uAulSoTdhIAtjqBkdUWZgNeetrlHQoqxJsK6FhP42kJLZUqXvQzIneO23fZJB7wZn4CMi/2EoCvsNIaPR86cG5jrKzO2La7dH5zs2YEa4SyLB4cOSd0M45M2p0KJ2T6xRqubPOQ7SSZYTAXcR6UQECgYEA6T1TJn/z8tP8amOWKeFZgbWQYCutfwVhJjaPrZm/NtHten7ftZBnvZagclMLrOBHeVFEPeFSC58up1Imtwp0ZT1WbaoHpR5I2LHcOZ7Rg/JC3rAjAE0W9uWrqkKaR77BdhFQfs8bdaqPypYB4az/zBgeHNYIkvAquQ4nv8DrMSECgYEAnTTd3CJXKgBmlycanQk8dnE89L4lFjYiQdFshZtV4dvBTPd47kU7fPZ9RQcOL4nioFdKdmzoHr2JSAu6ltq77TbisFsbvdRcvp23oh1dvgjQObC1gukkQFej28h2YzWtBYUmN+rGXMgEb6UAcVXB5370Wme+Zub1v+GVc38WMCsCgYBzHNIiCTqEGT3V4CqnptG/I7YK0OPC8gu9iWYl/uCRlNBJCb8tZATfXCz536S+gL6l0IcGp2MP21NyPyheZGmH4dr7KtS1GJpJYJbZVVoAbhu0vme36VQxLK8py89LI4ll1SvOOjdKPpDTIm/xSqnAuBJ8luIKa0AarzLM/9DUIQKBgQCMEKlHVBVjJ75AGCgfGDaVtOjBipSSiKLXD5doJvFK7bf5Mli9ulN5UEhmcxXRh0Gy6HNAtmHN2cNxvHl/pN1hSdCJnnNGG+qSLwWI3C9EfKfBbs8aF00kQrGMxbutQwqoa2yUz4ny6ocBTfrp/6Vm83cVAW/kUQ1N69hzchy7xwKBgA7mEp2zuZACTdd302i8RlecnCwkgumophk+o/tYgFKSvneAlUuUcM2N6GBpXmn7Q4xbZiCka7U7/iotUrGSiKym+Zm6KWcmcBRCLU4tQhhZFgaAHHeZ6oEsJCQrWmLfjKtrTDt9qBS+a6SyFVRldF+Ot4joSndIyZrYZ+uYoRu7
        SSH_USER=ubuntu
        
        # Save the private key content to a file
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # SSH into the EC2 instance and execute commands
        ssh -i key.pem $SSH_USER@$EC2_IP 'bash -s' << 'EOF'
          # Your deployment commands here
          docker build -t ezopsimg .
          docker stop ezopsconteiner || true
          docker rm ezopsconteiner || true
          docker run -d -p 49160:8080 --name ezopsconteiner ezopsimg
        EOF
